// <auto-generated />
using System;
using BugraLife.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugraLife.Migrations
{
    [DbContext(typeof(BugraLifeDBContext))]
    [Migration("20251214194347_gider_turu_tablosuna_aciklama_getirildi")]
    partial class gider_turu_tablosuna_aciklama_getirildi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BugraLife.Models.Asset", b =>
                {
                    b.Property<int>("asset_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asset_id"));

                    b.Property<decimal>("asset_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("asset_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("asset_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ingredient_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.HasKey("asset_id");

                    b.HasIndex("ingredient_id");

                    b.HasIndex("person_id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("BugraLife.Models.Daily", b =>
                {
                    b.Property<int>("daily_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("daily_id"));

                    b.Property<DateTime>("daily_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("daily_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("daily_status")
                        .HasColumnType("int");

                    b.HasKey("daily_id");

                    b.ToTable("Dailies");
                });

            modelBuilder.Entity("BugraLife.Models.Debtor", b =>
                {
                    b.Property<int>("debtor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("debtor_id"));

                    b.Property<string>("debtor_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("debtor_id");

                    b.ToTable("Debtors");
                });

            modelBuilder.Entity("BugraLife.Models.Expense", b =>
                {
                    b.Property<int>("expense_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expense_id"));

                    b.Property<decimal>("expense_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("expense_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("expense_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("expensetype_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_bankmovement")
                        .HasColumnType("bit");

                    b.Property<int>("paymenttype_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.HasKey("expense_id");

                    b.HasIndex("expensetype_id");

                    b.HasIndex("paymenttype_id");

                    b.HasIndex("person_id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BugraLife.Models.ExpenseType", b =>
                {
                    b.Property<int>("expensetype_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expensetype_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expensetype_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expensetype_order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_bank")
                        .HasColumnType("bit");

                    b.Property<bool>("is_home")
                        .HasColumnType("bit");

                    b.HasKey("expensetype_id");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("BugraLife.Models.Income", b =>
                {
                    b.Property<int>("income_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("income_id"));

                    b.Property<decimal>("income_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("income_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("income_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("incometype_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_bankmovement")
                        .HasColumnType("bit");

                    b.Property<int>("paymenttype_id")
                        .HasColumnType("int");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.HasKey("income_id");

                    b.HasIndex("incometype_id");

                    b.HasIndex("paymenttype_id");

                    b.HasIndex("person_id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("BugraLife.Models.IncomeType", b =>
                {
                    b.Property<int>("incometype_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("incometype_id"));

                    b.Property<string>("incometype_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("incometype_order")
                        .HasColumnType("int");

                    b.Property<bool>("is_bank")
                        .HasColumnType("bit");

                    b.HasKey("incometype_id");

                    b.ToTable("IncomeTypes");
                });

            modelBuilder.Entity("BugraLife.Models.Ingredient", b =>
                {
                    b.Property<int>("ingredient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ingredient_id"));

                    b.Property<string>("ingredient_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ingredient_id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("BugraLife.Models.Location", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("location_id"));

                    b.Property<string>("location_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BugraLife.Models.LoginUser", b =>
                {
                    b.Property<int>("loginuser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loginuser_id"));

                    b.Property<string>("login_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginuser_namesurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loginuser_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("loginuser_id");

                    b.ToTable("LoginUser");
                });

            modelBuilder.Entity("BugraLife.Models.Movement", b =>
                {
                    b.Property<int>("movement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("movement_id"));

                    b.Property<int>("debtor_id")
                        .HasColumnType("int");

                    b.Property<int>("ingredient_id")
                        .HasColumnType("int");

                    b.Property<decimal>("movement_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("movement_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("movement_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("person_id")
                        .HasColumnType("int");

                    b.HasKey("movement_id");

                    b.HasIndex("debtor_id");

                    b.HasIndex("ingredient_id");

                    b.HasIndex("person_id");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("BugraLife.Models.PaymentType", b =>
                {
                    b.Property<int>("paymenttype_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymenttype_id"));

                    b.Property<bool>("is_bank")
                        .HasColumnType("bit");

                    b.Property<decimal>("paymenttype_balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("paymenttype_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymenttype_order")
                        .HasColumnType("int");

                    b.HasKey("paymenttype_id");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("BugraLife.Models.Person", b =>
                {
                    b.Property<int>("person_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("person_id"));

                    b.Property<bool>("is_bank")
                        .HasColumnType("bit");

                    b.Property<string>("person_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("person_order")
                        .HasColumnType("int");

                    b.HasKey("person_id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BugraLife.Models.PlannedToDo", b =>
                {
                    b.Property<int>("plannedtodo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("plannedtodo_id"));

                    b.Property<DateTime>("plannedtodo_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("plannedtodo_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("plannedtodo_done")
                        .HasColumnType("bit");

                    b.HasKey("plannedtodo_id");

                    b.ToTable("PlannedToDos");
                });

            modelBuilder.Entity("BugraLife.Models.UnPlannedToDo", b =>
                {
                    b.Property<int>("unplannedtodo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unplannedtodo_id"));

                    b.Property<DateTime>("unplannedtodo_createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("unplannedtodo_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("unplannedtodo_done")
                        .HasColumnType("bit");

                    b.HasKey("unplannedtodo_id");

                    b.ToTable("UnPlannedToDos");
                });

            modelBuilder.Entity("BugraLife.Models.WebSite", b =>
                {
                    b.Property<int>("website_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("website_id"));

                    b.Property<string>("website_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("website_id");

                    b.ToTable("WebSites");
                });

            modelBuilder.Entity("BugraLife.Models.WebSitePassword", b =>
                {
                    b.Property<int>("websitepassword_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("websitepassword_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("website_id")
                        .HasColumnType("int");

                    b.Property<string>("websitepassword_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("websitepassword_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("websitepassword_username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("websitepassword_id");

                    b.HasIndex("website_id");

                    b.ToTable("WebSitePasswords");
                });

            modelBuilder.Entity("BugraLife.Models.Asset", b =>
                {
                    b.HasOne("BugraLife.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BugraLife.Models.Expense", b =>
                {
                    b.HasOne("BugraLife.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("expensetype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("paymenttype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");

                    b.Navigation("PaymentType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BugraLife.Models.Income", b =>
                {
                    b.HasOne("BugraLife.Models.IncomeType", "IncomeType")
                        .WithMany()
                        .HasForeignKey("incometype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("paymenttype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeType");

                    b.Navigation("PaymentType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BugraLife.Models.Movement", b =>
                {
                    b.HasOne("BugraLife.Models.Debtor", "Debtor")
                        .WithMany()
                        .HasForeignKey("debtor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BugraLife.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debtor");

                    b.Navigation("Ingredient");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BugraLife.Models.WebSitePassword", b =>
                {
                    b.HasOne("BugraLife.Models.WebSite", "WebSite")
                        .WithMany()
                        .HasForeignKey("website_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebSite");
                });
#pragma warning restore 612, 618
        }
    }
}
